################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/Poco/Net/AbstractHTTPRequestHandler.cpp \
../src/Poco/Net/DNS.cpp \
../src/Poco/Net/DatagramSocket.cpp \
../src/Poco/Net/DatagramSocketImpl.cpp \
../src/Poco/Net/DialogSocket.cpp \
../src/Poco/Net/FTPClientSession.cpp \
../src/Poco/Net/FTPStreamFactory.cpp \
../src/Poco/Net/FilePartSource.cpp \
../src/Poco/Net/HTMLForm.cpp \
../src/Poco/Net/HTTPAuthenticationParams.cpp \
../src/Poco/Net/HTTPBasicCredentials.cpp \
../src/Poco/Net/HTTPBufferAllocator.cpp \
../src/Poco/Net/HTTPChunkedStream.cpp \
../src/Poco/Net/HTTPClientSession.cpp \
../src/Poco/Net/HTTPCookie.cpp \
../src/Poco/Net/HTTPCredentials.cpp \
../src/Poco/Net/HTTPDigestCredentials.cpp \
../src/Poco/Net/HTTPFixedLengthStream.cpp \
../src/Poco/Net/HTTPHeaderStream.cpp \
../src/Poco/Net/HTTPIOStream.cpp \
../src/Poco/Net/HTTPMessage.cpp \
../src/Poco/Net/HTTPRequest.cpp \
../src/Poco/Net/HTTPRequestHandler.cpp \
../src/Poco/Net/HTTPRequestHandlerFactory.cpp \
../src/Poco/Net/HTTPResponse.cpp \
../src/Poco/Net/HTTPServer.cpp \
../src/Poco/Net/HTTPServerConnection.cpp \
../src/Poco/Net/HTTPServerConnectionFactory.cpp \
../src/Poco/Net/HTTPServerParams.cpp \
../src/Poco/Net/HTTPServerRequest.cpp \
../src/Poco/Net/HTTPServerRequestImpl.cpp \
../src/Poco/Net/HTTPServerResponse.cpp \
../src/Poco/Net/HTTPServerResponseImpl.cpp \
../src/Poco/Net/HTTPServerSession.cpp \
../src/Poco/Net/HTTPSession.cpp \
../src/Poco/Net/HTTPSessionFactory.cpp \
../src/Poco/Net/HTTPSessionInstantiator.cpp \
../src/Poco/Net/HTTPStream.cpp \
../src/Poco/Net/HTTPStreamFactory.cpp \
../src/Poco/Net/HostEntry.cpp \
../src/Poco/Net/ICMPClient.cpp \
../src/Poco/Net/ICMPEventArgs.cpp \
../src/Poco/Net/ICMPPacket.cpp \
../src/Poco/Net/ICMPPacketImpl.cpp \
../src/Poco/Net/ICMPSocket.cpp \
../src/Poco/Net/ICMPSocketImpl.cpp \
../src/Poco/Net/ICMPv4PacketImpl.cpp \
../src/Poco/Net/IPAddress.cpp \
../src/Poco/Net/IPAddressImpl.cpp \
../src/Poco/Net/MailMessage.cpp \
../src/Poco/Net/MailRecipient.cpp \
../src/Poco/Net/MailStream.cpp \
../src/Poco/Net/MediaType.cpp \
../src/Poco/Net/MessageHeader.cpp \
../src/Poco/Net/MulticastSocket.cpp \
../src/Poco/Net/MultipartReader.cpp \
../src/Poco/Net/MultipartWriter.cpp \
../src/Poco/Net/NTPClient.cpp \
../src/Poco/Net/NTPEventArgs.cpp \
../src/Poco/Net/NTPPacket.cpp \
../src/Poco/Net/NameValueCollection.cpp \
../src/Poco/Net/Net.cpp \
../src/Poco/Net/NetException.cpp \
../src/Poco/Net/NetworkInterface.cpp \
../src/Poco/Net/NullPartHandler.cpp \
../src/Poco/Net/OAuth10Credentials.cpp \
../src/Poco/Net/OAuth20Credentials.cpp \
../src/Poco/Net/POP3ClientSession.cpp \
../src/Poco/Net/PartHandler.cpp \
../src/Poco/Net/PartSource.cpp \
../src/Poco/Net/PartStore.cpp \
../src/Poco/Net/QuotedPrintableDecoder.cpp \
../src/Poco/Net/QuotedPrintableEncoder.cpp \
../src/Poco/Net/RawSocket.cpp \
../src/Poco/Net/RawSocketImpl.cpp \
../src/Poco/Net/RemoteSyslogChannel.cpp \
../src/Poco/Net/RemoteSyslogListener.cpp \
../src/Poco/Net/SMTPChannel.cpp \
../src/Poco/Net/SMTPClientSession.cpp \
../src/Poco/Net/ServerSocket.cpp \
../src/Poco/Net/ServerSocketImpl.cpp \
../src/Poco/Net/Socket.cpp \
../src/Poco/Net/SocketAddress.cpp \
../src/Poco/Net/SocketAddressImpl.cpp \
../src/Poco/Net/SocketImpl.cpp \
../src/Poco/Net/SocketNotification.cpp \
../src/Poco/Net/SocketNotifier.cpp \
../src/Poco/Net/SocketReactor.cpp \
../src/Poco/Net/SocketStream.cpp \
../src/Poco/Net/StreamSocket.cpp \
../src/Poco/Net/StreamSocketImpl.cpp \
../src/Poco/Net/StringPartSource.cpp \
../src/Poco/Net/TCPServer.cpp \
../src/Poco/Net/TCPServerConnection.cpp \
../src/Poco/Net/TCPServerConnectionFactory.cpp \
../src/Poco/Net/TCPServerDispatcher.cpp \
../src/Poco/Net/TCPServerParams.cpp \
../src/Poco/Net/WebSocket.cpp \
../src/Poco/Net/WebSocketImpl.cpp 

OBJS += \
./src/Poco/Net/AbstractHTTPRequestHandler.o \
./src/Poco/Net/DNS.o \
./src/Poco/Net/DatagramSocket.o \
./src/Poco/Net/DatagramSocketImpl.o \
./src/Poco/Net/DialogSocket.o \
./src/Poco/Net/FTPClientSession.o \
./src/Poco/Net/FTPStreamFactory.o \
./src/Poco/Net/FilePartSource.o \
./src/Poco/Net/HTMLForm.o \
./src/Poco/Net/HTTPAuthenticationParams.o \
./src/Poco/Net/HTTPBasicCredentials.o \
./src/Poco/Net/HTTPBufferAllocator.o \
./src/Poco/Net/HTTPChunkedStream.o \
./src/Poco/Net/HTTPClientSession.o \
./src/Poco/Net/HTTPCookie.o \
./src/Poco/Net/HTTPCredentials.o \
./src/Poco/Net/HTTPDigestCredentials.o \
./src/Poco/Net/HTTPFixedLengthStream.o \
./src/Poco/Net/HTTPHeaderStream.o \
./src/Poco/Net/HTTPIOStream.o \
./src/Poco/Net/HTTPMessage.o \
./src/Poco/Net/HTTPRequest.o \
./src/Poco/Net/HTTPRequestHandler.o \
./src/Poco/Net/HTTPRequestHandlerFactory.o \
./src/Poco/Net/HTTPResponse.o \
./src/Poco/Net/HTTPServer.o \
./src/Poco/Net/HTTPServerConnection.o \
./src/Poco/Net/HTTPServerConnectionFactory.o \
./src/Poco/Net/HTTPServerParams.o \
./src/Poco/Net/HTTPServerRequest.o \
./src/Poco/Net/HTTPServerRequestImpl.o \
./src/Poco/Net/HTTPServerResponse.o \
./src/Poco/Net/HTTPServerResponseImpl.o \
./src/Poco/Net/HTTPServerSession.o \
./src/Poco/Net/HTTPSession.o \
./src/Poco/Net/HTTPSessionFactory.o \
./src/Poco/Net/HTTPSessionInstantiator.o \
./src/Poco/Net/HTTPStream.o \
./src/Poco/Net/HTTPStreamFactory.o \
./src/Poco/Net/HostEntry.o \
./src/Poco/Net/ICMPClient.o \
./src/Poco/Net/ICMPEventArgs.o \
./src/Poco/Net/ICMPPacket.o \
./src/Poco/Net/ICMPPacketImpl.o \
./src/Poco/Net/ICMPSocket.o \
./src/Poco/Net/ICMPSocketImpl.o \
./src/Poco/Net/ICMPv4PacketImpl.o \
./src/Poco/Net/IPAddress.o \
./src/Poco/Net/IPAddressImpl.o \
./src/Poco/Net/MailMessage.o \
./src/Poco/Net/MailRecipient.o \
./src/Poco/Net/MailStream.o \
./src/Poco/Net/MediaType.o \
./src/Poco/Net/MessageHeader.o \
./src/Poco/Net/MulticastSocket.o \
./src/Poco/Net/MultipartReader.o \
./src/Poco/Net/MultipartWriter.o \
./src/Poco/Net/NTPClient.o \
./src/Poco/Net/NTPEventArgs.o \
./src/Poco/Net/NTPPacket.o \
./src/Poco/Net/NameValueCollection.o \
./src/Poco/Net/Net.o \
./src/Poco/Net/NetException.o \
./src/Poco/Net/NetworkInterface.o \
./src/Poco/Net/NullPartHandler.o \
./src/Poco/Net/OAuth10Credentials.o \
./src/Poco/Net/OAuth20Credentials.o \
./src/Poco/Net/POP3ClientSession.o \
./src/Poco/Net/PartHandler.o \
./src/Poco/Net/PartSource.o \
./src/Poco/Net/PartStore.o \
./src/Poco/Net/QuotedPrintableDecoder.o \
./src/Poco/Net/QuotedPrintableEncoder.o \
./src/Poco/Net/RawSocket.o \
./src/Poco/Net/RawSocketImpl.o \
./src/Poco/Net/RemoteSyslogChannel.o \
./src/Poco/Net/RemoteSyslogListener.o \
./src/Poco/Net/SMTPChannel.o \
./src/Poco/Net/SMTPClientSession.o \
./src/Poco/Net/ServerSocket.o \
./src/Poco/Net/ServerSocketImpl.o \
./src/Poco/Net/Socket.o \
./src/Poco/Net/SocketAddress.o \
./src/Poco/Net/SocketAddressImpl.o \
./src/Poco/Net/SocketImpl.o \
./src/Poco/Net/SocketNotification.o \
./src/Poco/Net/SocketNotifier.o \
./src/Poco/Net/SocketReactor.o \
./src/Poco/Net/SocketStream.o \
./src/Poco/Net/StreamSocket.o \
./src/Poco/Net/StreamSocketImpl.o \
./src/Poco/Net/StringPartSource.o \
./src/Poco/Net/TCPServer.o \
./src/Poco/Net/TCPServerConnection.o \
./src/Poco/Net/TCPServerConnectionFactory.o \
./src/Poco/Net/TCPServerDispatcher.o \
./src/Poco/Net/TCPServerParams.o \
./src/Poco/Net/WebSocket.o \
./src/Poco/Net/WebSocketImpl.o 

CPP_DEPS += \
./src/Poco/Net/AbstractHTTPRequestHandler.d \
./src/Poco/Net/DNS.d \
./src/Poco/Net/DatagramSocket.d \
./src/Poco/Net/DatagramSocketImpl.d \
./src/Poco/Net/DialogSocket.d \
./src/Poco/Net/FTPClientSession.d \
./src/Poco/Net/FTPStreamFactory.d \
./src/Poco/Net/FilePartSource.d \
./src/Poco/Net/HTMLForm.d \
./src/Poco/Net/HTTPAuthenticationParams.d \
./src/Poco/Net/HTTPBasicCredentials.d \
./src/Poco/Net/HTTPBufferAllocator.d \
./src/Poco/Net/HTTPChunkedStream.d \
./src/Poco/Net/HTTPClientSession.d \
./src/Poco/Net/HTTPCookie.d \
./src/Poco/Net/HTTPCredentials.d \
./src/Poco/Net/HTTPDigestCredentials.d \
./src/Poco/Net/HTTPFixedLengthStream.d \
./src/Poco/Net/HTTPHeaderStream.d \
./src/Poco/Net/HTTPIOStream.d \
./src/Poco/Net/HTTPMessage.d \
./src/Poco/Net/HTTPRequest.d \
./src/Poco/Net/HTTPRequestHandler.d \
./src/Poco/Net/HTTPRequestHandlerFactory.d \
./src/Poco/Net/HTTPResponse.d \
./src/Poco/Net/HTTPServer.d \
./src/Poco/Net/HTTPServerConnection.d \
./src/Poco/Net/HTTPServerConnectionFactory.d \
./src/Poco/Net/HTTPServerParams.d \
./src/Poco/Net/HTTPServerRequest.d \
./src/Poco/Net/HTTPServerRequestImpl.d \
./src/Poco/Net/HTTPServerResponse.d \
./src/Poco/Net/HTTPServerResponseImpl.d \
./src/Poco/Net/HTTPServerSession.d \
./src/Poco/Net/HTTPSession.d \
./src/Poco/Net/HTTPSessionFactory.d \
./src/Poco/Net/HTTPSessionInstantiator.d \
./src/Poco/Net/HTTPStream.d \
./src/Poco/Net/HTTPStreamFactory.d \
./src/Poco/Net/HostEntry.d \
./src/Poco/Net/ICMPClient.d \
./src/Poco/Net/ICMPEventArgs.d \
./src/Poco/Net/ICMPPacket.d \
./src/Poco/Net/ICMPPacketImpl.d \
./src/Poco/Net/ICMPSocket.d \
./src/Poco/Net/ICMPSocketImpl.d \
./src/Poco/Net/ICMPv4PacketImpl.d \
./src/Poco/Net/IPAddress.d \
./src/Poco/Net/IPAddressImpl.d \
./src/Poco/Net/MailMessage.d \
./src/Poco/Net/MailRecipient.d \
./src/Poco/Net/MailStream.d \
./src/Poco/Net/MediaType.d \
./src/Poco/Net/MessageHeader.d \
./src/Poco/Net/MulticastSocket.d \
./src/Poco/Net/MultipartReader.d \
./src/Poco/Net/MultipartWriter.d \
./src/Poco/Net/NTPClient.d \
./src/Poco/Net/NTPEventArgs.d \
./src/Poco/Net/NTPPacket.d \
./src/Poco/Net/NameValueCollection.d \
./src/Poco/Net/Net.d \
./src/Poco/Net/NetException.d \
./src/Poco/Net/NetworkInterface.d \
./src/Poco/Net/NullPartHandler.d \
./src/Poco/Net/OAuth10Credentials.d \
./src/Poco/Net/OAuth20Credentials.d \
./src/Poco/Net/POP3ClientSession.d \
./src/Poco/Net/PartHandler.d \
./src/Poco/Net/PartSource.d \
./src/Poco/Net/PartStore.d \
./src/Poco/Net/QuotedPrintableDecoder.d \
./src/Poco/Net/QuotedPrintableEncoder.d \
./src/Poco/Net/RawSocket.d \
./src/Poco/Net/RawSocketImpl.d \
./src/Poco/Net/RemoteSyslogChannel.d \
./src/Poco/Net/RemoteSyslogListener.d \
./src/Poco/Net/SMTPChannel.d \
./src/Poco/Net/SMTPClientSession.d \
./src/Poco/Net/ServerSocket.d \
./src/Poco/Net/ServerSocketImpl.d \
./src/Poco/Net/Socket.d \
./src/Poco/Net/SocketAddress.d \
./src/Poco/Net/SocketAddressImpl.d \
./src/Poco/Net/SocketImpl.d \
./src/Poco/Net/SocketNotification.d \
./src/Poco/Net/SocketNotifier.d \
./src/Poco/Net/SocketReactor.d \
./src/Poco/Net/SocketStream.d \
./src/Poco/Net/StreamSocket.d \
./src/Poco/Net/StreamSocketImpl.d \
./src/Poco/Net/StringPartSource.d \
./src/Poco/Net/TCPServer.d \
./src/Poco/Net/TCPServerConnection.d \
./src/Poco/Net/TCPServerConnectionFactory.d \
./src/Poco/Net/TCPServerDispatcher.d \
./src/Poco/Net/TCPServerParams.d \
./src/Poco/Net/WebSocket.d \
./src/Poco/Net/WebSocketImpl.d 


# Each subdirectory must supply rules for building sources it contributes
src/Poco/Net/%.o: ../src/Poco/Net/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"E:\Projects\Arm\code\Core\src" -I"E:\Projects\Arm\code\TrajectoryCore\src" -O0 -g3 -Wall -c -fmessage-length=0  -std=c++11 -U__STRICT_ANSI__ -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


