################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../src/Poco/bignum-dtoa.cc \
../src/Poco/bignum.cc \
../src/Poco/cached-powers.cc \
../src/Poco/diy-fp.cc \
../src/Poco/double-conversion.cc \
../src/Poco/fast-dtoa.cc \
../src/Poco/fixed-dtoa.cc \
../src/Poco/strtod.cc 

CPP_SRCS += \
../src/Poco/ASCIIEncoding.cpp \
../src/Poco/AbstractContainerNode.cpp \
../src/Poco/AbstractNode.cpp \
../src/Poco/AbstractObserver.cpp \
../src/Poco/ActiveDispatcher.cpp \
../src/Poco/ArchiveStrategy.cpp \
../src/Poco/Ascii.cpp \
../src/Poco/AsyncChannel.cpp \
../src/Poco/AtomicCounter.cpp \
../src/Poco/Attr.cpp \
../src/Poco/AttrMap.cpp \
../src/Poco/Attributes.cpp \
../src/Poco/AttributesImpl.cpp \
../src/Poco/Base32Decoder.cpp \
../src/Poco/Base32Encoder.cpp \
../src/Poco/Base64Decoder.cpp \
../src/Poco/Base64Encoder.cpp \
../src/Poco/BinaryReader.cpp \
../src/Poco/BinaryWriter.cpp \
../src/Poco/Bugcheck.cpp \
../src/Poco/ByteOrder.cpp \
../src/Poco/CDATASection.cpp \
../src/Poco/Channel.cpp \
../src/Poco/CharacterData.cpp \
../src/Poco/Checksum.cpp \
../src/Poco/ChildNodesList.cpp \
../src/Poco/Clock.cpp \
../src/Poco/Comment.cpp \
../src/Poco/Condition.cpp \
../src/Poco/Configurable.cpp \
../src/Poco/ConsoleChannel.cpp \
../src/Poco/ContentHandler.cpp \
../src/Poco/CountingStream.cpp \
../src/Poco/DOMBuilder.cpp \
../src/Poco/DOMException.cpp \
../src/Poco/DOMImplementation.cpp \
../src/Poco/DOMObject.cpp \
../src/Poco/DOMParser.cpp \
../src/Poco/DOMSerializer.cpp \
../src/Poco/DOMWriter.cpp \
../src/Poco/DTDHandler.cpp \
../src/Poco/DTDMap.cpp \
../src/Poco/DateTime.cpp \
../src/Poco/DateTimeFormat.cpp \
../src/Poco/DateTimeFormatter.cpp \
../src/Poco/DateTimeParser.cpp \
../src/Poco/Debugger.cpp \
../src/Poco/DeclHandler.cpp \
../src/Poco/DefaultHandler.cpp \
../src/Poco/DeflatingStream.cpp \
../src/Poco/DigestEngine.cpp \
../src/Poco/DigestStream.cpp \
../src/Poco/DirectoryIterator.cpp \
../src/Poco/DirectoryIteratorStrategy.cpp \
../src/Poco/DirectoryIterator_UNIX.cpp \
../src/Poco/DirectoryIterator_WIN32U.cpp \
../src/Poco/DirectoryWatcher.cpp \
../src/Poco/Document.cpp \
../src/Poco/DocumentEvent.cpp \
../src/Poco/DocumentFragment.cpp \
../src/Poco/DocumentType.cpp \
../src/Poco/Element.cpp \
../src/Poco/ElementsByTagNameList.cpp \
../src/Poco/Entity.cpp \
../src/Poco/EntityReference.cpp \
../src/Poco/EntityResolver.cpp \
../src/Poco/EntityResolverImpl.cpp \
../src/Poco/Environment.cpp \
../src/Poco/Environment_WIN32U.cpp \
../src/Poco/Error.cpp \
../src/Poco/ErrorHandler.cpp \
../src/Poco/Event.cpp \
../src/Poco/EventArgs.cpp \
../src/Poco/EventChannel.cpp \
../src/Poco/EventDispatcher.cpp \
../src/Poco/EventException.cpp \
../src/Poco/EventListener.cpp \
../src/Poco/EventLogChannel.cpp \
../src/Poco/EventTarget.cpp \
../src/Poco/Event_POSIX.cpp \
../src/Poco/Event_VX.cpp \
../src/Poco/Event_WIN32.cpp \
../src/Poco/Exception.cpp \
../src/Poco/FIFOBufferStream.cpp \
../src/Poco/FPEnvironment.cpp \
../src/Poco/FPEnvironment_C99.cpp \
../src/Poco/FPEnvironment_DEC.cpp \
../src/Poco/FPEnvironment_DUMMY.cpp \
../src/Poco/FPEnvironment_SUN.cpp \
../src/Poco/FPEnvironment_WIN32.cpp \
../src/Poco/File.cpp \
../src/Poco/FileChannel.cpp \
../src/Poco/FileStream.cpp \
../src/Poco/FileStreamFactory.cpp \
../src/Poco/FileStream_POSIX.cpp \
../src/Poco/FileStream_WIN32.cpp \
../src/Poco/File_WIN32U.cpp \
../src/Poco/Format.cpp \
../src/Poco/Formatter.cpp \
../src/Poco/FormattingChannel.cpp \
../src/Poco/Glob.cpp \
../src/Poco/Hash.cpp \
../src/Poco/HashStatistic.cpp \
../src/Poco/HexBinaryDecoder.cpp \
../src/Poco/HexBinaryEncoder.cpp \
../src/Poco/InflatingStream.cpp \
../src/Poco/InputSource.cpp \
../src/Poco/Latin1Encoding.cpp \
../src/Poco/Latin2Encoding.cpp \
../src/Poco/Latin9Encoding.cpp \
../src/Poco/LexicalHandler.cpp \
../src/Poco/LineEndingConverter.cpp \
../src/Poco/LocalDateTime.cpp \
../src/Poco/Locator.cpp \
../src/Poco/LocatorImpl.cpp \
../src/Poco/LogFile.cpp \
../src/Poco/LogFile_STD.cpp \
../src/Poco/LogFile_VMS.cpp \
../src/Poco/LogFile_WIN32.cpp \
../src/Poco/LogFile_WIN32U.cpp \
../src/Poco/LogStream.cpp \
../src/Poco/Logger.cpp \
../src/Poco/LoggingFactory.cpp \
../src/Poco/LoggingRegistry.cpp \
../src/Poco/MD4Engine.cpp \
../src/Poco/MD5Engine.cpp \
../src/Poco/Manifest.cpp \
../src/Poco/MemoryPool.cpp \
../src/Poco/MemoryStream.cpp \
../src/Poco/Message.cpp \
../src/Poco/MutationEvent.cpp \
../src/Poco/Mutex.cpp \
../src/Poco/Mutex_POSIX.cpp \
../src/Poco/Mutex_VX.cpp \
../src/Poco/Mutex_WIN32.cpp \
../src/Poco/Mutex_WINCE.cpp \
../src/Poco/Name.cpp \
../src/Poco/NamePool.cpp \
../src/Poco/NamedEvent.cpp \
../src/Poco/NamedEvent_Android.cpp \
../src/Poco/NamedEvent_UNIX.cpp \
../src/Poco/NamedEvent_VMS.cpp \
../src/Poco/NamedEvent_WIN32.cpp \
../src/Poco/NamedEvent_WIN32U.cpp \
../src/Poco/NamedMutex.cpp \
../src/Poco/NamedMutex_Android.cpp \
../src/Poco/NamedMutex_UNIX.cpp \
../src/Poco/NamedMutex_VMS.cpp \
../src/Poco/NamedMutex_WIN32.cpp \
../src/Poco/NamedMutex_WIN32U.cpp \
../src/Poco/NamedNodeMap.cpp \
../src/Poco/NamespaceStrategy.cpp \
../src/Poco/NamespaceSupport.cpp \
../src/Poco/NestedDiagnosticContext.cpp \
../src/Poco/Node.cpp \
../src/Poco/NodeAppender.cpp \
../src/Poco/NodeFilter.cpp \
../src/Poco/NodeIterator.cpp \
../src/Poco/NodeList.cpp \
../src/Poco/Notation.cpp \
../src/Poco/Notification.cpp \
../src/Poco/NotificationCenter.cpp \
../src/Poco/NotificationQueue.cpp \
../src/Poco/NullChannel.cpp \
../src/Poco/NullStream.cpp \
../src/Poco/NumberFormatter.cpp \
../src/Poco/NumberParser.cpp \
../src/Poco/NumericString.cpp \
../src/Poco/OpcomChannel.cpp \
../src/Poco/ParserEngine.cpp \
../src/Poco/Path.cpp \
../src/Poco/Path_UNIX.cpp \
../src/Poco/Path_VMS.cpp \
../src/Poco/Path_WIN32.cpp \
../src/Poco/Path_WIN32U.cpp \
../src/Poco/Path_WINCE.cpp \
../src/Poco/PatternFormatter.cpp \
../src/Poco/Pipe.cpp \
../src/Poco/PipeImpl.cpp \
../src/Poco/PipeImpl_DUMMY.cpp \
../src/Poco/PipeImpl_POSIX.cpp \
../src/Poco/PipeImpl_WIN32.cpp \
../src/Poco/PipeStream.cpp \
../src/Poco/PriorityNotificationQueue.cpp \
../src/Poco/Process.cpp \
../src/Poco/Process_UNIX.cpp \
../src/Poco/Process_VMS.cpp \
../src/Poco/Process_VX.cpp \
../src/Poco/Process_WIN32.cpp \
../src/Poco/Process_WIN32U.cpp \
../src/Poco/Process_WINCE.cpp \
../src/Poco/ProcessingInstruction.cpp \
../src/Poco/PurgeStrategy.cpp \
../src/Poco/RWLock.cpp \
../src/Poco/RWLock_Android.cpp \
../src/Poco/RWLock_POSIX.cpp \
../src/Poco/RWLock_VX.cpp \
../src/Poco/RWLock_WIN32.cpp \
../src/Poco/RWLock_WINCE.cpp \
../src/Poco/Random.cpp \
../src/Poco/RandomStream.cpp \
../src/Poco/RefCountedObject.cpp \
../src/Poco/RegularExpression.cpp \
../src/Poco/RotateStrategy.cpp \
../src/Poco/Runnable.cpp \
../src/Poco/SAXException.cpp \
../src/Poco/SAXParser.cpp \
../src/Poco/SHA1Engine.cpp \
../src/Poco/Semaphore.cpp \
../src/Poco/Semaphore_POSIX.cpp \
../src/Poco/Semaphore_VX.cpp \
../src/Poco/Semaphore_WIN32.cpp \
../src/Poco/SharedLibrary.cpp \
../src/Poco/SharedLibrary_HPUX.cpp \
../src/Poco/SharedLibrary_UNIX.cpp \
../src/Poco/SharedLibrary_VMS.cpp \
../src/Poco/SharedLibrary_VX.cpp \
../src/Poco/SharedLibrary_WIN32.cpp \
../src/Poco/SharedLibrary_WIN32U.cpp \
../src/Poco/SharedMemory.cpp \
../src/Poco/SharedMemory_DUMMY.cpp \
../src/Poco/SharedMemory_POSIX.cpp \
../src/Poco/SharedMemory_WIN32.cpp \
../src/Poco/SignalHandler.cpp \
../src/Poco/SimpleFileChannel.cpp \
../src/Poco/SortedDirectoryIterator.cpp \
../src/Poco/SplitterChannel.cpp \
../src/Poco/Stopwatch.cpp \
../src/Poco/StreamChannel.cpp \
../src/Poco/StreamConverter.cpp \
../src/Poco/StreamCopier.cpp \
../src/Poco/StreamTokenizer.cpp \
../src/Poco/String.cpp \
../src/Poco/StringTokenizer.cpp \
../src/Poco/SynchronizedObject.cpp \
../src/Poco/SyslogChannel.cpp \
../src/Poco/Task.cpp \
../src/Poco/TaskManager.cpp \
../src/Poco/TaskNotification.cpp \
../src/Poco/TeeStream.cpp \
../src/Poco/TemporaryFile.cpp \
../src/Poco/Text.cpp \
../src/Poco/TextBufferIterator.cpp \
../src/Poco/TextConverter.cpp \
../src/Poco/TextEncoding.cpp \
../src/Poco/TextIterator.cpp \
../src/Poco/Thread.cpp \
../src/Poco/ThreadLocal.cpp \
../src/Poco/ThreadPool.cpp \
../src/Poco/ThreadTarget.cpp \
../src/Poco/Thread_POSIX.cpp \
../src/Poco/Thread_VX.cpp \
../src/Poco/Thread_WIN32.cpp \
../src/Poco/Thread_WINCE.cpp \
../src/Poco/TimedNotificationQueue.cpp \
../src/Poco/Timer.cpp \
../src/Poco/Timespan.cpp \
../src/Poco/Timestamp.cpp \
../src/Poco/Timezone.cpp \
../src/Poco/Timezone_UNIX.cpp \
../src/Poco/Timezone_VX.cpp \
../src/Poco/Timezone_WIN32.cpp \
../src/Poco/Timezone_WINCE.cpp \
../src/Poco/Token.cpp \
../src/Poco/TreeWalker.cpp \
../src/Poco/URI.cpp \
../src/Poco/URIStreamFactory.cpp \
../src/Poco/URIStreamOpener.cpp \
../src/Poco/UTF16Encoding.cpp \
../src/Poco/UTF32Encoding.cpp \
../src/Poco/UTF8Encoding.cpp \
../src/Poco/UTF8String.cpp \
../src/Poco/UUID.cpp \
../src/Poco/UUIDGenerator.cpp \
../src/Poco/Unicode.cpp \
../src/Poco/UnicodeConverter.cpp \
../src/Poco/Var.cpp \
../src/Poco/VarHolder.cpp \
../src/Poco/VarIterator.cpp \
../src/Poco/Void.cpp \
../src/Poco/WhitespaceFilter.cpp \
../src/Poco/Windows1250Encoding.cpp \
../src/Poco/Windows1251Encoding.cpp \
../src/Poco/Windows1252Encoding.cpp \
../src/Poco/WindowsConsoleChannel.cpp \
../src/Poco/XMLException.cpp \
../src/Poco/XMLFilter.cpp \
../src/Poco/XMLFilterImpl.cpp \
../src/Poco/XMLReader.cpp \
../src/Poco/XMLString.cpp \
../src/Poco/XMLWriter.cpp \
../src/Poco/xmlparse.cpp 

C_SRCS += \
../src/Poco/adler32.c \
../src/Poco/compress.c \
../src/Poco/crc32.c \
../src/Poco/deflate.c \
../src/Poco/infback.c \
../src/Poco/inffast.c \
../src/Poco/inflate.c \
../src/Poco/inftrees.c \
../src/Poco/pcre_byte_order.c \
../src/Poco/pcre_chartables.c \
../src/Poco/pcre_compile.c \
../src/Poco/pcre_config.c \
../src/Poco/pcre_dfa_exec.c \
../src/Poco/pcre_exec.c \
../src/Poco/pcre_fullinfo.c \
../src/Poco/pcre_get.c \
../src/Poco/pcre_globals.c \
../src/Poco/pcre_jit_compile.c \
../src/Poco/pcre_maketables.c \
../src/Poco/pcre_newline.c \
../src/Poco/pcre_ord2utf8.c \
../src/Poco/pcre_refcount.c \
../src/Poco/pcre_string_utils.c \
../src/Poco/pcre_study.c \
../src/Poco/pcre_tables.c \
../src/Poco/pcre_ucd.c \
../src/Poco/pcre_valid_utf8.c \
../src/Poco/pcre_version.c \
../src/Poco/pcre_xclass.c \
../src/Poco/trees.c \
../src/Poco/xmlrole.c \
../src/Poco/xmltok.c \
../src/Poco/xmltok_impl.c \
../src/Poco/xmltok_ns.c \
../src/Poco/zutil.c 

CC_DEPS += \
./src/Poco/bignum-dtoa.d \
./src/Poco/bignum.d \
./src/Poco/cached-powers.d \
./src/Poco/diy-fp.d \
./src/Poco/double-conversion.d \
./src/Poco/fast-dtoa.d \
./src/Poco/fixed-dtoa.d \
./src/Poco/strtod.d 

OBJS += \
./src/Poco/ASCIIEncoding.o \
./src/Poco/AbstractContainerNode.o \
./src/Poco/AbstractNode.o \
./src/Poco/AbstractObserver.o \
./src/Poco/ActiveDispatcher.o \
./src/Poco/ArchiveStrategy.o \
./src/Poco/Ascii.o \
./src/Poco/AsyncChannel.o \
./src/Poco/AtomicCounter.o \
./src/Poco/Attr.o \
./src/Poco/AttrMap.o \
./src/Poco/Attributes.o \
./src/Poco/AttributesImpl.o \
./src/Poco/Base32Decoder.o \
./src/Poco/Base32Encoder.o \
./src/Poco/Base64Decoder.o \
./src/Poco/Base64Encoder.o \
./src/Poco/BinaryReader.o \
./src/Poco/BinaryWriter.o \
./src/Poco/Bugcheck.o \
./src/Poco/ByteOrder.o \
./src/Poco/CDATASection.o \
./src/Poco/Channel.o \
./src/Poco/CharacterData.o \
./src/Poco/Checksum.o \
./src/Poco/ChildNodesList.o \
./src/Poco/Clock.o \
./src/Poco/Comment.o \
./src/Poco/Condition.o \
./src/Poco/Configurable.o \
./src/Poco/ConsoleChannel.o \
./src/Poco/ContentHandler.o \
./src/Poco/CountingStream.o \
./src/Poco/DOMBuilder.o \
./src/Poco/DOMException.o \
./src/Poco/DOMImplementation.o \
./src/Poco/DOMObject.o \
./src/Poco/DOMParser.o \
./src/Poco/DOMSerializer.o \
./src/Poco/DOMWriter.o \
./src/Poco/DTDHandler.o \
./src/Poco/DTDMap.o \
./src/Poco/DateTime.o \
./src/Poco/DateTimeFormat.o \
./src/Poco/DateTimeFormatter.o \
./src/Poco/DateTimeParser.o \
./src/Poco/Debugger.o \
./src/Poco/DeclHandler.o \
./src/Poco/DefaultHandler.o \
./src/Poco/DeflatingStream.o \
./src/Poco/DigestEngine.o \
./src/Poco/DigestStream.o \
./src/Poco/DirectoryIterator.o \
./src/Poco/DirectoryIteratorStrategy.o \
./src/Poco/DirectoryIterator_UNIX.o \
./src/Poco/DirectoryIterator_WIN32U.o \
./src/Poco/DirectoryWatcher.o \
./src/Poco/Document.o \
./src/Poco/DocumentEvent.o \
./src/Poco/DocumentFragment.o \
./src/Poco/DocumentType.o \
./src/Poco/Element.o \
./src/Poco/ElementsByTagNameList.o \
./src/Poco/Entity.o \
./src/Poco/EntityReference.o \
./src/Poco/EntityResolver.o \
./src/Poco/EntityResolverImpl.o \
./src/Poco/Environment.o \
./src/Poco/Environment_WIN32U.o \
./src/Poco/Error.o \
./src/Poco/ErrorHandler.o \
./src/Poco/Event.o \
./src/Poco/EventArgs.o \
./src/Poco/EventChannel.o \
./src/Poco/EventDispatcher.o \
./src/Poco/EventException.o \
./src/Poco/EventListener.o \
./src/Poco/EventLogChannel.o \
./src/Poco/EventTarget.o \
./src/Poco/Event_POSIX.o \
./src/Poco/Event_VX.o \
./src/Poco/Event_WIN32.o \
./src/Poco/Exception.o \
./src/Poco/FIFOBufferStream.o \
./src/Poco/FPEnvironment.o \
./src/Poco/FPEnvironment_C99.o \
./src/Poco/FPEnvironment_DEC.o \
./src/Poco/FPEnvironment_DUMMY.o \
./src/Poco/FPEnvironment_SUN.o \
./src/Poco/FPEnvironment_WIN32.o \
./src/Poco/File.o \
./src/Poco/FileChannel.o \
./src/Poco/FileStream.o \
./src/Poco/FileStreamFactory.o \
./src/Poco/FileStream_POSIX.o \
./src/Poco/FileStream_WIN32.o \
./src/Poco/File_WIN32U.o \
./src/Poco/Format.o \
./src/Poco/Formatter.o \
./src/Poco/FormattingChannel.o \
./src/Poco/Glob.o \
./src/Poco/Hash.o \
./src/Poco/HashStatistic.o \
./src/Poco/HexBinaryDecoder.o \
./src/Poco/HexBinaryEncoder.o \
./src/Poco/InflatingStream.o \
./src/Poco/InputSource.o \
./src/Poco/Latin1Encoding.o \
./src/Poco/Latin2Encoding.o \
./src/Poco/Latin9Encoding.o \
./src/Poco/LexicalHandler.o \
./src/Poco/LineEndingConverter.o \
./src/Poco/LocalDateTime.o \
./src/Poco/Locator.o \
./src/Poco/LocatorImpl.o \
./src/Poco/LogFile.o \
./src/Poco/LogFile_STD.o \
./src/Poco/LogFile_VMS.o \
./src/Poco/LogFile_WIN32.o \
./src/Poco/LogFile_WIN32U.o \
./src/Poco/LogStream.o \
./src/Poco/Logger.o \
./src/Poco/LoggingFactory.o \
./src/Poco/LoggingRegistry.o \
./src/Poco/MD4Engine.o \
./src/Poco/MD5Engine.o \
./src/Poco/Manifest.o \
./src/Poco/MemoryPool.o \
./src/Poco/MemoryStream.o \
./src/Poco/Message.o \
./src/Poco/MutationEvent.o \
./src/Poco/Mutex.o \
./src/Poco/Mutex_POSIX.o \
./src/Poco/Mutex_VX.o \
./src/Poco/Mutex_WIN32.o \
./src/Poco/Mutex_WINCE.o \
./src/Poco/Name.o \
./src/Poco/NamePool.o \
./src/Poco/NamedEvent.o \
./src/Poco/NamedEvent_Android.o \
./src/Poco/NamedEvent_UNIX.o \
./src/Poco/NamedEvent_VMS.o \
./src/Poco/NamedEvent_WIN32.o \
./src/Poco/NamedEvent_WIN32U.o \
./src/Poco/NamedMutex.o \
./src/Poco/NamedMutex_Android.o \
./src/Poco/NamedMutex_UNIX.o \
./src/Poco/NamedMutex_VMS.o \
./src/Poco/NamedMutex_WIN32.o \
./src/Poco/NamedMutex_WIN32U.o \
./src/Poco/NamedNodeMap.o \
./src/Poco/NamespaceStrategy.o \
./src/Poco/NamespaceSupport.o \
./src/Poco/NestedDiagnosticContext.o \
./src/Poco/Node.o \
./src/Poco/NodeAppender.o \
./src/Poco/NodeFilter.o \
./src/Poco/NodeIterator.o \
./src/Poco/NodeList.o \
./src/Poco/Notation.o \
./src/Poco/Notification.o \
./src/Poco/NotificationCenter.o \
./src/Poco/NotificationQueue.o \
./src/Poco/NullChannel.o \
./src/Poco/NullStream.o \
./src/Poco/NumberFormatter.o \
./src/Poco/NumberParser.o \
./src/Poco/NumericString.o \
./src/Poco/OpcomChannel.o \
./src/Poco/ParserEngine.o \
./src/Poco/Path.o \
./src/Poco/Path_UNIX.o \
./src/Poco/Path_VMS.o \
./src/Poco/Path_WIN32.o \
./src/Poco/Path_WIN32U.o \
./src/Poco/Path_WINCE.o \
./src/Poco/PatternFormatter.o \
./src/Poco/Pipe.o \
./src/Poco/PipeImpl.o \
./src/Poco/PipeImpl_DUMMY.o \
./src/Poco/PipeImpl_POSIX.o \
./src/Poco/PipeImpl_WIN32.o \
./src/Poco/PipeStream.o \
./src/Poco/PriorityNotificationQueue.o \
./src/Poco/Process.o \
./src/Poco/Process_UNIX.o \
./src/Poco/Process_VMS.o \
./src/Poco/Process_VX.o \
./src/Poco/Process_WIN32.o \
./src/Poco/Process_WIN32U.o \
./src/Poco/Process_WINCE.o \
./src/Poco/ProcessingInstruction.o \
./src/Poco/PurgeStrategy.o \
./src/Poco/RWLock.o \
./src/Poco/RWLock_Android.o \
./src/Poco/RWLock_POSIX.o \
./src/Poco/RWLock_VX.o \
./src/Poco/RWLock_WIN32.o \
./src/Poco/RWLock_WINCE.o \
./src/Poco/Random.o \
./src/Poco/RandomStream.o \
./src/Poco/RefCountedObject.o \
./src/Poco/RegularExpression.o \
./src/Poco/RotateStrategy.o \
./src/Poco/Runnable.o \
./src/Poco/SAXException.o \
./src/Poco/SAXParser.o \
./src/Poco/SHA1Engine.o \
./src/Poco/Semaphore.o \
./src/Poco/Semaphore_POSIX.o \
./src/Poco/Semaphore_VX.o \
./src/Poco/Semaphore_WIN32.o \
./src/Poco/SharedLibrary.o \
./src/Poco/SharedLibrary_HPUX.o \
./src/Poco/SharedLibrary_UNIX.o \
./src/Poco/SharedLibrary_VMS.o \
./src/Poco/SharedLibrary_VX.o \
./src/Poco/SharedLibrary_WIN32.o \
./src/Poco/SharedLibrary_WIN32U.o \
./src/Poco/SharedMemory.o \
./src/Poco/SharedMemory_DUMMY.o \
./src/Poco/SharedMemory_POSIX.o \
./src/Poco/SharedMemory_WIN32.o \
./src/Poco/SignalHandler.o \
./src/Poco/SimpleFileChannel.o \
./src/Poco/SortedDirectoryIterator.o \
./src/Poco/SplitterChannel.o \
./src/Poco/Stopwatch.o \
./src/Poco/StreamChannel.o \
./src/Poco/StreamConverter.o \
./src/Poco/StreamCopier.o \
./src/Poco/StreamTokenizer.o \
./src/Poco/String.o \
./src/Poco/StringTokenizer.o \
./src/Poco/SynchronizedObject.o \
./src/Poco/SyslogChannel.o \
./src/Poco/Task.o \
./src/Poco/TaskManager.o \
./src/Poco/TaskNotification.o \
./src/Poco/TeeStream.o \
./src/Poco/TemporaryFile.o \
./src/Poco/Text.o \
./src/Poco/TextBufferIterator.o \
./src/Poco/TextConverter.o \
./src/Poco/TextEncoding.o \
./src/Poco/TextIterator.o \
./src/Poco/Thread.o \
./src/Poco/ThreadLocal.o \
./src/Poco/ThreadPool.o \
./src/Poco/ThreadTarget.o \
./src/Poco/Thread_POSIX.o \
./src/Poco/Thread_VX.o \
./src/Poco/Thread_WIN32.o \
./src/Poco/Thread_WINCE.o \
./src/Poco/TimedNotificationQueue.o \
./src/Poco/Timer.o \
./src/Poco/Timespan.o \
./src/Poco/Timestamp.o \
./src/Poco/Timezone.o \
./src/Poco/Timezone_UNIX.o \
./src/Poco/Timezone_VX.o \
./src/Poco/Timezone_WIN32.o \
./src/Poco/Timezone_WINCE.o \
./src/Poco/Token.o \
./src/Poco/TreeWalker.o \
./src/Poco/URI.o \
./src/Poco/URIStreamFactory.o \
./src/Poco/URIStreamOpener.o \
./src/Poco/UTF16Encoding.o \
./src/Poco/UTF32Encoding.o \
./src/Poco/UTF8Encoding.o \
./src/Poco/UTF8String.o \
./src/Poco/UUID.o \
./src/Poco/UUIDGenerator.o \
./src/Poco/Unicode.o \
./src/Poco/UnicodeConverter.o \
./src/Poco/Var.o \
./src/Poco/VarHolder.o \
./src/Poco/VarIterator.o \
./src/Poco/Void.o \
./src/Poco/WhitespaceFilter.o \
./src/Poco/Windows1250Encoding.o \
./src/Poco/Windows1251Encoding.o \
./src/Poco/Windows1252Encoding.o \
./src/Poco/WindowsConsoleChannel.o \
./src/Poco/XMLException.o \
./src/Poco/XMLFilter.o \
./src/Poco/XMLFilterImpl.o \
./src/Poco/XMLReader.o \
./src/Poco/XMLString.o \
./src/Poco/XMLWriter.o \
./src/Poco/adler32.o \
./src/Poco/bignum-dtoa.o \
./src/Poco/bignum.o \
./src/Poco/cached-powers.o \
./src/Poco/compress.o \
./src/Poco/crc32.o \
./src/Poco/deflate.o \
./src/Poco/diy-fp.o \
./src/Poco/double-conversion.o \
./src/Poco/fast-dtoa.o \
./src/Poco/fixed-dtoa.o \
./src/Poco/infback.o \
./src/Poco/inffast.o \
./src/Poco/inflate.o \
./src/Poco/inftrees.o \
./src/Poco/pcre_byte_order.o \
./src/Poco/pcre_chartables.o \
./src/Poco/pcre_compile.o \
./src/Poco/pcre_config.o \
./src/Poco/pcre_dfa_exec.o \
./src/Poco/pcre_exec.o \
./src/Poco/pcre_fullinfo.o \
./src/Poco/pcre_get.o \
./src/Poco/pcre_globals.o \
./src/Poco/pcre_jit_compile.o \
./src/Poco/pcre_maketables.o \
./src/Poco/pcre_newline.o \
./src/Poco/pcre_ord2utf8.o \
./src/Poco/pcre_refcount.o \
./src/Poco/pcre_string_utils.o \
./src/Poco/pcre_study.o \
./src/Poco/pcre_tables.o \
./src/Poco/pcre_ucd.o \
./src/Poco/pcre_valid_utf8.o \
./src/Poco/pcre_version.o \
./src/Poco/pcre_xclass.o \
./src/Poco/strtod.o \
./src/Poco/trees.o \
./src/Poco/xmlparse.o \
./src/Poco/xmlrole.o \
./src/Poco/xmltok.o \
./src/Poco/xmltok_impl.o \
./src/Poco/xmltok_ns.o \
./src/Poco/zutil.o 

CPP_DEPS += \
./src/Poco/ASCIIEncoding.d \
./src/Poco/AbstractContainerNode.d \
./src/Poco/AbstractNode.d \
./src/Poco/AbstractObserver.d \
./src/Poco/ActiveDispatcher.d \
./src/Poco/ArchiveStrategy.d \
./src/Poco/Ascii.d \
./src/Poco/AsyncChannel.d \
./src/Poco/AtomicCounter.d \
./src/Poco/Attr.d \
./src/Poco/AttrMap.d \
./src/Poco/Attributes.d \
./src/Poco/AttributesImpl.d \
./src/Poco/Base32Decoder.d \
./src/Poco/Base32Encoder.d \
./src/Poco/Base64Decoder.d \
./src/Poco/Base64Encoder.d \
./src/Poco/BinaryReader.d \
./src/Poco/BinaryWriter.d \
./src/Poco/Bugcheck.d \
./src/Poco/ByteOrder.d \
./src/Poco/CDATASection.d \
./src/Poco/Channel.d \
./src/Poco/CharacterData.d \
./src/Poco/Checksum.d \
./src/Poco/ChildNodesList.d \
./src/Poco/Clock.d \
./src/Poco/Comment.d \
./src/Poco/Condition.d \
./src/Poco/Configurable.d \
./src/Poco/ConsoleChannel.d \
./src/Poco/ContentHandler.d \
./src/Poco/CountingStream.d \
./src/Poco/DOMBuilder.d \
./src/Poco/DOMException.d \
./src/Poco/DOMImplementation.d \
./src/Poco/DOMObject.d \
./src/Poco/DOMParser.d \
./src/Poco/DOMSerializer.d \
./src/Poco/DOMWriter.d \
./src/Poco/DTDHandler.d \
./src/Poco/DTDMap.d \
./src/Poco/DateTime.d \
./src/Poco/DateTimeFormat.d \
./src/Poco/DateTimeFormatter.d \
./src/Poco/DateTimeParser.d \
./src/Poco/Debugger.d \
./src/Poco/DeclHandler.d \
./src/Poco/DefaultHandler.d \
./src/Poco/DeflatingStream.d \
./src/Poco/DigestEngine.d \
./src/Poco/DigestStream.d \
./src/Poco/DirectoryIterator.d \
./src/Poco/DirectoryIteratorStrategy.d \
./src/Poco/DirectoryIterator_UNIX.d \
./src/Poco/DirectoryIterator_WIN32U.d \
./src/Poco/DirectoryWatcher.d \
./src/Poco/Document.d \
./src/Poco/DocumentEvent.d \
./src/Poco/DocumentFragment.d \
./src/Poco/DocumentType.d \
./src/Poco/Element.d \
./src/Poco/ElementsByTagNameList.d \
./src/Poco/Entity.d \
./src/Poco/EntityReference.d \
./src/Poco/EntityResolver.d \
./src/Poco/EntityResolverImpl.d \
./src/Poco/Environment.d \
./src/Poco/Environment_WIN32U.d \
./src/Poco/Error.d \
./src/Poco/ErrorHandler.d \
./src/Poco/Event.d \
./src/Poco/EventArgs.d \
./src/Poco/EventChannel.d \
./src/Poco/EventDispatcher.d \
./src/Poco/EventException.d \
./src/Poco/EventListener.d \
./src/Poco/EventLogChannel.d \
./src/Poco/EventTarget.d \
./src/Poco/Event_POSIX.d \
./src/Poco/Event_VX.d \
./src/Poco/Event_WIN32.d \
./src/Poco/Exception.d \
./src/Poco/FIFOBufferStream.d \
./src/Poco/FPEnvironment.d \
./src/Poco/FPEnvironment_C99.d \
./src/Poco/FPEnvironment_DEC.d \
./src/Poco/FPEnvironment_DUMMY.d \
./src/Poco/FPEnvironment_SUN.d \
./src/Poco/FPEnvironment_WIN32.d \
./src/Poco/File.d \
./src/Poco/FileChannel.d \
./src/Poco/FileStream.d \
./src/Poco/FileStreamFactory.d \
./src/Poco/FileStream_POSIX.d \
./src/Poco/FileStream_WIN32.d \
./src/Poco/File_WIN32U.d \
./src/Poco/Format.d \
./src/Poco/Formatter.d \
./src/Poco/FormattingChannel.d \
./src/Poco/Glob.d \
./src/Poco/Hash.d \
./src/Poco/HashStatistic.d \
./src/Poco/HexBinaryDecoder.d \
./src/Poco/HexBinaryEncoder.d \
./src/Poco/InflatingStream.d \
./src/Poco/InputSource.d \
./src/Poco/Latin1Encoding.d \
./src/Poco/Latin2Encoding.d \
./src/Poco/Latin9Encoding.d \
./src/Poco/LexicalHandler.d \
./src/Poco/LineEndingConverter.d \
./src/Poco/LocalDateTime.d \
./src/Poco/Locator.d \
./src/Poco/LocatorImpl.d \
./src/Poco/LogFile.d \
./src/Poco/LogFile_STD.d \
./src/Poco/LogFile_VMS.d \
./src/Poco/LogFile_WIN32.d \
./src/Poco/LogFile_WIN32U.d \
./src/Poco/LogStream.d \
./src/Poco/Logger.d \
./src/Poco/LoggingFactory.d \
./src/Poco/LoggingRegistry.d \
./src/Poco/MD4Engine.d \
./src/Poco/MD5Engine.d \
./src/Poco/Manifest.d \
./src/Poco/MemoryPool.d \
./src/Poco/MemoryStream.d \
./src/Poco/Message.d \
./src/Poco/MutationEvent.d \
./src/Poco/Mutex.d \
./src/Poco/Mutex_POSIX.d \
./src/Poco/Mutex_VX.d \
./src/Poco/Mutex_WIN32.d \
./src/Poco/Mutex_WINCE.d \
./src/Poco/Name.d \
./src/Poco/NamePool.d \
./src/Poco/NamedEvent.d \
./src/Poco/NamedEvent_Android.d \
./src/Poco/NamedEvent_UNIX.d \
./src/Poco/NamedEvent_VMS.d \
./src/Poco/NamedEvent_WIN32.d \
./src/Poco/NamedEvent_WIN32U.d \
./src/Poco/NamedMutex.d \
./src/Poco/NamedMutex_Android.d \
./src/Poco/NamedMutex_UNIX.d \
./src/Poco/NamedMutex_VMS.d \
./src/Poco/NamedMutex_WIN32.d \
./src/Poco/NamedMutex_WIN32U.d \
./src/Poco/NamedNodeMap.d \
./src/Poco/NamespaceStrategy.d \
./src/Poco/NamespaceSupport.d \
./src/Poco/NestedDiagnosticContext.d \
./src/Poco/Node.d \
./src/Poco/NodeAppender.d \
./src/Poco/NodeFilter.d \
./src/Poco/NodeIterator.d \
./src/Poco/NodeList.d \
./src/Poco/Notation.d \
./src/Poco/Notification.d \
./src/Poco/NotificationCenter.d \
./src/Poco/NotificationQueue.d \
./src/Poco/NullChannel.d \
./src/Poco/NullStream.d \
./src/Poco/NumberFormatter.d \
./src/Poco/NumberParser.d \
./src/Poco/NumericString.d \
./src/Poco/OpcomChannel.d \
./src/Poco/ParserEngine.d \
./src/Poco/Path.d \
./src/Poco/Path_UNIX.d \
./src/Poco/Path_VMS.d \
./src/Poco/Path_WIN32.d \
./src/Poco/Path_WIN32U.d \
./src/Poco/Path_WINCE.d \
./src/Poco/PatternFormatter.d \
./src/Poco/Pipe.d \
./src/Poco/PipeImpl.d \
./src/Poco/PipeImpl_DUMMY.d \
./src/Poco/PipeImpl_POSIX.d \
./src/Poco/PipeImpl_WIN32.d \
./src/Poco/PipeStream.d \
./src/Poco/PriorityNotificationQueue.d \
./src/Poco/Process.d \
./src/Poco/Process_UNIX.d \
./src/Poco/Process_VMS.d \
./src/Poco/Process_VX.d \
./src/Poco/Process_WIN32.d \
./src/Poco/Process_WIN32U.d \
./src/Poco/Process_WINCE.d \
./src/Poco/ProcessingInstruction.d \
./src/Poco/PurgeStrategy.d \
./src/Poco/RWLock.d \
./src/Poco/RWLock_Android.d \
./src/Poco/RWLock_POSIX.d \
./src/Poco/RWLock_VX.d \
./src/Poco/RWLock_WIN32.d \
./src/Poco/RWLock_WINCE.d \
./src/Poco/Random.d \
./src/Poco/RandomStream.d \
./src/Poco/RefCountedObject.d \
./src/Poco/RegularExpression.d \
./src/Poco/RotateStrategy.d \
./src/Poco/Runnable.d \
./src/Poco/SAXException.d \
./src/Poco/SAXParser.d \
./src/Poco/SHA1Engine.d \
./src/Poco/Semaphore.d \
./src/Poco/Semaphore_POSIX.d \
./src/Poco/Semaphore_VX.d \
./src/Poco/Semaphore_WIN32.d \
./src/Poco/SharedLibrary.d \
./src/Poco/SharedLibrary_HPUX.d \
./src/Poco/SharedLibrary_UNIX.d \
./src/Poco/SharedLibrary_VMS.d \
./src/Poco/SharedLibrary_VX.d \
./src/Poco/SharedLibrary_WIN32.d \
./src/Poco/SharedLibrary_WIN32U.d \
./src/Poco/SharedMemory.d \
./src/Poco/SharedMemory_DUMMY.d \
./src/Poco/SharedMemory_POSIX.d \
./src/Poco/SharedMemory_WIN32.d \
./src/Poco/SignalHandler.d \
./src/Poco/SimpleFileChannel.d \
./src/Poco/SortedDirectoryIterator.d \
./src/Poco/SplitterChannel.d \
./src/Poco/Stopwatch.d \
./src/Poco/StreamChannel.d \
./src/Poco/StreamConverter.d \
./src/Poco/StreamCopier.d \
./src/Poco/StreamTokenizer.d \
./src/Poco/String.d \
./src/Poco/StringTokenizer.d \
./src/Poco/SynchronizedObject.d \
./src/Poco/SyslogChannel.d \
./src/Poco/Task.d \
./src/Poco/TaskManager.d \
./src/Poco/TaskNotification.d \
./src/Poco/TeeStream.d \
./src/Poco/TemporaryFile.d \
./src/Poco/Text.d \
./src/Poco/TextBufferIterator.d \
./src/Poco/TextConverter.d \
./src/Poco/TextEncoding.d \
./src/Poco/TextIterator.d \
./src/Poco/Thread.d \
./src/Poco/ThreadLocal.d \
./src/Poco/ThreadPool.d \
./src/Poco/ThreadTarget.d \
./src/Poco/Thread_POSIX.d \
./src/Poco/Thread_VX.d \
./src/Poco/Thread_WIN32.d \
./src/Poco/Thread_WINCE.d \
./src/Poco/TimedNotificationQueue.d \
./src/Poco/Timer.d \
./src/Poco/Timespan.d \
./src/Poco/Timestamp.d \
./src/Poco/Timezone.d \
./src/Poco/Timezone_UNIX.d \
./src/Poco/Timezone_VX.d \
./src/Poco/Timezone_WIN32.d \
./src/Poco/Timezone_WINCE.d \
./src/Poco/Token.d \
./src/Poco/TreeWalker.d \
./src/Poco/URI.d \
./src/Poco/URIStreamFactory.d \
./src/Poco/URIStreamOpener.d \
./src/Poco/UTF16Encoding.d \
./src/Poco/UTF32Encoding.d \
./src/Poco/UTF8Encoding.d \
./src/Poco/UTF8String.d \
./src/Poco/UUID.d \
./src/Poco/UUIDGenerator.d \
./src/Poco/Unicode.d \
./src/Poco/UnicodeConverter.d \
./src/Poco/Var.d \
./src/Poco/VarHolder.d \
./src/Poco/VarIterator.d \
./src/Poco/Void.d \
./src/Poco/WhitespaceFilter.d \
./src/Poco/Windows1250Encoding.d \
./src/Poco/Windows1251Encoding.d \
./src/Poco/Windows1252Encoding.d \
./src/Poco/WindowsConsoleChannel.d \
./src/Poco/XMLException.d \
./src/Poco/XMLFilter.d \
./src/Poco/XMLFilterImpl.d \
./src/Poco/XMLReader.d \
./src/Poco/XMLString.d \
./src/Poco/XMLWriter.d \
./src/Poco/xmlparse.d 

C_DEPS += \
./src/Poco/adler32.d \
./src/Poco/compress.d \
./src/Poco/crc32.d \
./src/Poco/deflate.d \
./src/Poco/infback.d \
./src/Poco/inffast.d \
./src/Poco/inflate.d \
./src/Poco/inftrees.d \
./src/Poco/pcre_byte_order.d \
./src/Poco/pcre_chartables.d \
./src/Poco/pcre_compile.d \
./src/Poco/pcre_config.d \
./src/Poco/pcre_dfa_exec.d \
./src/Poco/pcre_exec.d \
./src/Poco/pcre_fullinfo.d \
./src/Poco/pcre_get.d \
./src/Poco/pcre_globals.d \
./src/Poco/pcre_jit_compile.d \
./src/Poco/pcre_maketables.d \
./src/Poco/pcre_newline.d \
./src/Poco/pcre_ord2utf8.d \
./src/Poco/pcre_refcount.d \
./src/Poco/pcre_string_utils.d \
./src/Poco/pcre_study.d \
./src/Poco/pcre_tables.d \
./src/Poco/pcre_ucd.d \
./src/Poco/pcre_valid_utf8.d \
./src/Poco/pcre_version.d \
./src/Poco/pcre_xclass.d \
./src/Poco/trees.d \
./src/Poco/xmlrole.d \
./src/Poco/xmltok.d \
./src/Poco/xmltok_impl.d \
./src/Poco/xmltok_ns.d \
./src/Poco/zutil.d 


# Each subdirectory must supply rules for building sources it contributes
src/Poco/%.o: ../src/Poco/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"E:\Projects\Arm\code\Core\src" -I"E:\Projects\Arm\code\TrajectoryCore\src" -O0 -g3 -Wall -c -fmessage-length=0  -std=c++11 -U__STRICT_ANSI__ -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/Poco/%.o: ../src/Poco/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/Poco/%.o: ../src/Poco/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"E:\Projects\Arm\code\Core\src" -I"E:\Projects\Arm\code\TrajectoryCore\src" -O0 -g3 -Wall -c -fmessage-length=0  -std=c++11 -U__STRICT_ANSI__ -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


